// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// uq_vec
IntegerVector uq_vec(IntegerVector x);
RcppExport SEXP _jam_uq_vec(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(uq_vec(x));
    return rcpp_result_gen;
END_RCPP
}
// uq_chr
CharacterVector uq_chr(CharacterVector x);
RcppExport SEXP _jam_uq_chr(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(uq_chr(x));
    return rcpp_result_gen;
END_RCPP
}
// f3
bool f3(IntegerVector x);
RcppExport SEXP _jam_f3(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(f3(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_jam_uq_vec", (DL_FUNC) &_jam_uq_vec, 1},
    {"_jam_uq_chr", (DL_FUNC) &_jam_uq_chr, 1},
    {"_jam_f3", (DL_FUNC) &_jam_f3, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_jam(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
