# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

uq_vec <- function(x) {
    .Call(`_jam_uq_vec`, x)
}

uq_chr <- function(x) {
    .Call(`_jam_uq_chr`, x)
}

f3 <- function(x) {
    .Call(`_jam_f3`, x)
}

